# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Java-Swing
version:      0.12
version_from: Swing.pm
installdirs:  site
requires:
    Inline:                        0.44
    Inline::Java:                  0.47
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
