#!/usr/bin/perl
use strict; use warnings;

use Java::Swing::Generate::Listener;

# This program makes Java programs which implement listeners.

my $with_usage = "usage: $0 listener_file\n";
my $file       = shift or die $with_usage;

open FILE, "$file" or die "Couldn't read $file\n";

my $input = join "", <FILE>;
my $hash  = eval $input;

print generate_module($hash);

