#!/usr/bin/perl
use strict; use warnings;

use Java::Swing::Generate::Widget;

my $with_usage   = "usage: $0 package class [sub_package]\n";
my $package      = shift or die $with_usage;
my $class        = shift or die $with_usage;
my $sub_package  = shift;

my $module = generate($package, $class, $sub_package);

print $module;
